language:
  elixir

matrix:
  include:
    - otp_release: 20.3
      elixir: 1.6.6
    - otp_release: 21.0
      elixir: 1.7.3

services:
  - redis-server

script:
  - if [[ `elixir -v` = *"1.7"* ]]; then mix format --check-formatted; fi
  - mix test --trace
